# Generated by Django 6.0.4 on 2026-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('quality', models.CharField(choices=[('best', 'Best Quality'), ('1080', '1080p'), ('720', '720p'), ('480', '480p'), ('audio', 'Audio Only')], max_length=20)),
                ('download_thumbnail', models.BooleanField(default=False)),
                ('download_subtitle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
